apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: supplier-vs
  namespace: punchout
spec:
  gateways:
  - istio-system/cert-manager-gateway
  hosts:
  - supplier.zitaconseil.fr
  http:
  - route:
    - destination:
        host: supplier-simulator.punchout.svc.cluster.local
        port:
          number: 80
