apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: supplier-vs
  namespace: punchout
spec:
  gateways:
  - istio-system/cert-manager-gateway
  hosts:
  - supplier.zitaconseil.fr
  http:
  - route:
    - destination:
        host: supplier-simulator.punchout.svc.cluster.local
        port:
          number: 80

---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  labels:
    gateway: supplier-mtls-gateway-com
    istio: ingressgateway
  name: supplier-mtls-gateway-com
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - supplier.zitaconseil.fr
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: supplier-credential-mutual-tls
      mode: MUTUAL
