name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      id: buildAndPushImage
      uses: MaximilianoBz/dockerhub-buildpush@v1.0
      with:
        registry_url: 'docker.io'
        repository_name: 'supplier-simulator'
        user_name: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_version: 'latest'
        docker_file: '.'
        
    - name: Setup kubectl
      uses: ThomasKliszowski/setup-kubectl@v1
      with:
         # Base64 encoded kube config
         kube-config: ${{ secrets.KUBECONFIG_B64 }}

    - name: Apply Kubernetes manifests
      run: |
         kubectl version
         kubectl apply -f manifest/
         kubectl rollout restart deploy supplier-simulator -n punchout
         
          
    
            
